### ISSUE TITLE
iperf3 "-f bits" is not supported

### ISSUE THREAD

**Issue by christianuhlmann** [nerdalert/cloud-bandwidth#5]
Hi,

please check the documentation: [https://iperf.fr/iperf-doc.php](https://iperf.fr/iperf-doc.php)
> <html>
> <body>
> 
> 
> -f, --format [kmKM] | A letter specifying the format to print bandwidth numbers in. Supported formats are     'k' = Kbits/sec           'K' = KBytes/sec     'm' = Mbits/sec           'M' = MBytes/secThe adaptive formats choose between kilo- and mega- as appropriate.
> -- | --
> 
> 
> 
> </body>
> </html>

option -f only allow [kmgtKMGT]

Christian

**Comment by Venom1221** [comment]
Hi, I guess this is not fully solved, I was trying to run this today and after cloning the repo and configuring all nodes I get 
<nil> iperf3: parameter error - bad format specifier (valid formats are in the set [kmgtKMGT])
and that due to 
INFO[0000] Running shell command ->  [-c docker run -i --rm networkstatic/iperf3 -P 1 -R -t 5 -f bits -p 5201 -c x.x.x.x | tail -n 3 | head -n1 | awk '{print $7}']

**Comment by nerdalert** [comment]
Hi @Venom1221 yeah the supported formats in the ESNet fork is only `-f, --format   [kmgtKMGT] format to report: Kbits, Mbits, Gbits, Tbits`. 

iPerf 2.0 supported bits/bytes.  For reference, they mention the change from v2 to v3 in [iperf docs](https://iperf.fr/iperf-doc.php#3change)  `Change number output format (-f)`.

Cheers!
